#!/usr/bin/env bash
# The single source of truth for checks run locally and in CI.
set -euo pipefail

repo_root=$(git rev-parse --show-toplevel)
cd "$repo_root"

flutter pub get --enforce-lockfile

echo "== formatting =="
# patrol_test/test_bundle.dart is generated by Patrol and deliberately ignored.
dart format --output=none --set-exit-if-changed lib test integration_test test_driver patrol_test/notifications_test.dart

echo "== analyzing =="
flutter analyze

echo "== testing =="
flutter test
