name: Windows MSIX

on:
  workflow_dispatch:
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  build-msix:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
      - uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2
        with:
          flutter-version: 3.44.8
          channel: stable
          cache: true
      - run: flutter pub get
      - run: flutter build windows --release
      - run: dart run msix:create
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: scrubby-msix
          path: |
            build/windows/x64/runner/Release/*.msix
            build/windows/x64/runner/Release/*.msixupload
