name: Windows MSIX

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-msix:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
      - uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2
        with:
          flutter-version: 3.44.8
          channel: stable
          cache: true
      - run: flutter pub get
      - run: flutter build windows --release
      - name: Build MSIX
        run: dart run msix:create
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: scrubby-msix
          path: |
            build/windows/x64/runner/Release/*.msix
            build/windows/x64/runner/Release/*.msixupload
      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"
      - name: Setup Microsoft Store CLI
        uses: microsoft/setup-msstore-cli@v1
      - name: Configure Microsoft Store CLI
        run: msstore reconfigure --tenantId ${{ secrets.AZURE_TENANT_ID }} --clientId ${{ secrets.AZURE_CLIENT_ID }} --clientSecret ${{ secrets.AZURE_CLIENT_SECRET }} --sellerId ${{ secrets.SELLER_ID }}
      - name: Publish to Microsoft Store
        run: msstore publish --inputDirectory build/windows/x64/runner/Release --appId 9N17TVBTJWXD --packageRolloutPercentage 100
